---
# Ansible playbook

- name: Configuration for web servers
  hosts: webservers
  sudo: True
  roles:
  - web

- name: Configuration for ssh servers
  hosts: sshservers
  sudo: True
  roles:
  - ssh

- name: Configuration for ldap servers
  hosts: ldapservers
  sudo: True
  roles:
  - ldap
